name: foo
version: "0.1"
summary: The most useful snap in the world
description: |
  What did you expect?
grade: stable
confinement: strict

apps:
  foo:
    command: foo.sh 
    plugs: [network]
parts:
  foo:
    source: https://github.com/MariusQuabeck/foo-snap.git
    plugin: dump
    stage-packages: [gem, lolcat]



  
